version: '3.5'
services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network

  client:
    container_name: client
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - app_network

networks:
  app_network:
    name: app_network
